from setuptools import setup, find_packages

setup(
    name="onspotml",
    version="0.1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "numpy>=1.20.0",
        "pandas>=1.3.0",
        "scikit-learn>=1.0.0",
        "matplotlib>=3.4.0",
        "seaborn>=0.11.0",
        "requests>=2.26.0",
        "python-dotenv>=0.19.0",
    ],
    extras_require={
        "dev": [
            "pytest>=6.0",
            "pytest-cov>=2.0",
            "black>=21.0",
            "flake8>=3.9",
            "mypy>=0.910",
            "bandit>=1.7",
            "safety>=1.10",
            "pydocstyle>=6.0",
            "sphinx>=4.0",
            "sphinx-rtd-theme>=0.5",
            "pytest-benchmark>=3.4",
        ],
    },
    python_requires=">=3.8",
    author="prototyp33",
    description="Machine Learning project for parking spot prediction",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/prototyp33/OnSpotML",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
    ],
) 